categories_dict = {
    "do smarowania": {
        "dżemy i marmolady": [
            "dżem truskawkowy",
            "dżem brzoskwiniowy",
            "dżem owoce leśne",
            "dżem wiśniowy",
            "dżem owocowy",
            "marmolada wieloowocowa",
            "konfitura malinowa",
            "konfitura wiśniowa",
            "konfitura owoce leśne",
            "konfitura owocowa"
        ],
        "kremy": ["nutella", "masło orzechowe", "krem czekoladowy"],
        "pasty": ["pasta warzywna", "hummus", "pasta jajeczna", "pasta rybna"],
    },
    "nabiał": {
        "jaja i drożdże": ["jajko", "drożdże"],
        "jogurty i serki": [
            "serek homogenizowany",
            "serek naturalny",
            "jogurt naturalny",
            "jogurt z owocami",
            "skyr",
        ],
        "mleko i kefir": ["mleko", "zsiadłe mleko", "kefir", "maślanka"],
        "produkty twarogowe": ["twaróg", "almette", "serek twarogowy"],
        "sery": [
            "ser",
            "ser pleśniowy",
            "ser topiony",
            "ser tarty",
            "ser żółty",
            "serek topiony",
        ],
        "śmietany": ["śmietana", "śmietanka 30%"],
    },
    "napoje": {
        "alkohole": ["rum", "wódka", "whiskey", "wino białe", "wino czerwone", "piwo"],
        "napoje gazowane i ice tea": ["cola", "fanta", "sprite", "ice tea", "tonik"],
        "soki i nektary": [
            "sok pomarańczaowy",
            "sok jabłkowy",
            "sok ananasowy",
            "sok wieloowocowy",
            "sok multiwitamina",
            "nektar z czarnej porzeczki",
            "napój owocowy"
        ],
        "soki wyciskane": ["sok z cytryny", "sok z limonki", "sok z pomarańczy"],
        "syropy": ["syrop malinowy", "syrop truskawkowy", "syrop imbirowy"],
        "wody": ["woda", "woda gazowana", "woda lekko gazowana", "woda smakowa"],
    },
    "owoce, warzywa, orzechy i grzyby": {
        "owoce": ["jabłko", "gruszka", "malina", "truskawki", "winogrona", "limonka", "kiwi", "pomarańcza", "cytryna", "kaki", "mandarynka"],
        "warzywa": [
            "cebula",
            "czosnek",
            "pomidor",
            "fasola",
            "marchewka",
            "pietruszka",
            "papryka",
            "szpinak",
            "rukola",
            "sałata",
            "ziemniaki",
        ],
        "orzechy": ["orzech wloski", "orzech laskowy", "orzech nerkowca", "orzech ziemny", "pistacja"],
        "grzyby": ["kurka", "pieczarka", "grzyby mun", "prawdziwek"],
    },
    "pieczywo": {
        "bułki": ["kajzerka", "bułka z ziarnami", "bagietka", "bułka"],
        "chleby": ["chleb pszenny", "chleb tostowy", "chleb razowy", "chleb żytni"],
        "tortille": ["tortilla pszenna", "tortilla pełnoziarnista", "lawasz"],
        "zamienniki pieczywa": ["wafle ryżowe", "chlebki pełnoziarniste"],
    },
    "produkty gotowe": {
        "ciasta": ["ciasto na pizze", "ciasto francuskie"],
        "inne": ["kluski", "frytki", "kopytka"],
    },
    "produkty mięsne": {
        "konserwy i pasztety": [
            "konserwa mięsna",
            "konserwa rybna",
            "mielonka",
            "pasztet drobiowy",
            "pasztet wieprzowy",
        ],
        "ryby i owoce morza": [
            "dorsz",
            "makrela",
            "łosoś",
            "paluszki rybne",
            "krewetki",
        ],
        "świeże mięsa": [
            "filet z kurczaka",
            "mięso mielone",
            "mięso z kurczaka",
        ],
        "wędliny i mięsa w plastrach": [
            "szynka",
            "polędwica",
            "schab",
            "kiełbasa żywiecka",
            "salami"
        ],
        "kabanosy i kiełbasy": [
            "kabanosy drobiowe",
            "kabanosy wieprzowe",
            "kiełbasa"
        ]
    },
    "przyprawy i dodatki w proszku": {
        "przyprawy": [
            "cynamon",
            "kurkuma",
            "sól",
            "pieprz",
            "chilli",
            "słodka papryka",
            "oregano",
        ],
        "dodatki": [
            "kostka rosołowa",
            "soda oczyszczona",
            "proszek do pieczenia",
            "cukier waniliowy",
        ],
        "zioła": ["bazylia", "koperek", "mięta"],
    },
    "sosy i dodatki": {
        "ketchup, majonez i inne": [
            "ketchup",
            "majonez",
            "musztarda",
            "chrzan",
        ],
        "sosy": ["sos sojowy", "sos słodko-kwaśny", "sos czosnkowy"],
    },
    "spiżarnia": {
        "do słodzenia": ["cukier", "cukier waniliowy", "miód", "ksylitol"],
        "kasze": ["kasza gryczana", "kasza jaglana"],
        "kawa, kakao, herbata": [
            "kawa rozpuszczalna",
            "kawa ziarnista",
            "kawa sypana",
            "kakao",
            "herbata",
        ],
        "makarony": [
            "makaron",
            "makaron wstążki",
            "makaron spaghetti",
            "makaron lasagne",
        ],
        "mąki": ["mąka tortowa", "mąka pszenna", "mąka razowa", "mąka żytnia"],
        "octy": ["ocet jabłkowy", "ocet spirytusowy"],
        "produkty zbożowe": ["płatki owsiane", "otręby"],
        "puszki i słoiki": [
            "buraczki",
            "groszek",
            "pesto",
            "krojone pomidory",
            "pomidory suszone",
            "passata pomidorowa",
            "koncentrat pomidorowy",
            "fasola z puszki",
            "oliwki",
        ],
        "ryz": ["ryż", "ryż paraboiled", "ryż pełnoziarnisty"],
    },
    "tłuszcze": {
        "płynne": ["olej", "olej rzepakowy", "olej słonecznikowy", "oliwa"],
        "twarde": ["masło", "margaryna", "smalec"],
    },
    "inne": None
}
